# Generated by Django 5.2.12 on 2026-03-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike / Motorcycle'), ('heavy', 'Heavy Vehicle'), ('tempo', 'Tempo / Mini Truck')], max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(help_text='Total course length in days')),
                ('total_lessons', models.PositiveIntegerField(help_text='Number of practical driving sessions')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicles', models.ManyToManyField(blank=True, related_name='courses', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['vehicle_type', 'level'],
            },
        ),
    ]
