# Generated by Django 5.2.12 on 2026-03-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike / Motorcycle'), ('heavy', 'Heavy Vehicle'), ('tempo', 'Tempo / Mini Truck'), ('scooter', 'Scooter')], max_length=20),
        ),
    ]
