# Generated by Django 5.2.12 on 2026-03-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('vehicles', '0003_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='courses', to='vehicles.vehicle'),
        ),
    ]
