# Generated by Django 5.2.12 on 2026-04-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_vehicle_type'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['vehicle_type__name', 'level', 'course_name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='vehicles',
            field=models.ManyToManyField(blank=True, help_text='Select available vehicles for this course', related_name='courses', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='course',
            name='vehicle_type',
            field=models.ForeignKey(help_text='Select the category of vehicle for this course', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.vehicletype'),
        ),
    ]
