# Generated by Django 5.2.12 on 2026-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_vehicletype_alter_course_options_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('scooter', 'Scooter')], help_text='Select the type of vehicle for this course', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['vehicle_type', 'level', 'course_name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='vehicles',
            field=models.ManyToManyField(blank=True, help_text='Select vehicles available for this course', related_name='courses', to='vehicles.vehicle'),
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
