# Generated by Django 5.2.12 on 2026-04-09 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_vehicle_type_alter_course_options_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='course',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Select a vehicle for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='vehicles.vehicle'),
        ),
    ]
