# Generated by Django 5.2.12 on 2026-04-06 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='phone',
        ),
        migrations.AddField(
            model_name='trainee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
