# Generated by Django 5.2.12 on 2026-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_remove_trainee_address_remove_trainee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat discount amount in Rs.', max_digits=8),
        ),
    ]
