# Generated by Django 5.2.12 on 2026-05-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0003_trainee_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainees/photos/'),
        ),
    ]
