# Generated by Django 5.2.12 on 2026-05-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0004_trainee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='photo',
        ),
        migrations.AddField(
            model_name='trainee',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='trainees/images/'),
        ),
    ]
