# Generated by Django 5.2.12 on 2026-05-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0005_remove_trainee_photo_trainee_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='instructor_guidance',
            field=models.CharField(choices=[('auto', 'Auto (determined by policy)'), ('guided', 'Instructor-Guided'), ('free', 'Instructor-Free')], default='auto', help_text="Manual override for instructor requirement. 'auto' = system determines based on course level or policy. Set by supervisor/admin.", max_length=10),
        ),
        migrations.AddField(
            model_name='trainee',
            name='vehicle_type_preference',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike'), ('scooter', 'Scooter')], help_text='Vehicle type for pay-per-session trainees who have no course.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('TRAINING', 'In Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PAY_PER_SESSION', 'Pay-Per-Session')], default='ENROLLED', max_length=20),
        ),
    ]
