# Generated by Django 5.2.12 on 2026-04-11 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_remove_course_vehicles_course_vehicle'),
        ('trainees', '0002_remove_trainee_address_remove_trainee_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_records', to='courses.course')),
                ('trainee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_record', to='trainees.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.feerecord')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
