# Generated by Django 5.2.12 on 2026-05-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('e-wallets', 'e-Wallets'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
