# Generated by Django 5.2.12 on 2026-05-19 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_sessionpayment'),
        ('scheduling', '0007_schedulingconfig_public_booking_cutoff_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpayment',
            name='public_booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='scheduling.publicbooking'),
        ),
        migrations.AddField(
            model_name='sessionpayment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_payments_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
