# Generated by Django 5.2.12 on 2026-05-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_remove_instructor_email_remove_instructor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainees/images/'),
        ),
    ]
