# Generated by Django 5.2.12 on 2026-05-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_instructor_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='photo',
            new_name='images',
        ),
    ]
