# Generated by Django 5.2.12 on 2026-05-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_rename_photo_instructor_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/images/'),
        ),
    ]
