# Generated by Django 5.2.12 on 2026-05-25 11:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for the scenario (e.g. 'City Driving – Easy')", max_length=200, unique=True)),
                ('scenario_type', models.CharField(choices=[('city_driving', 'City Driving'), ('highway', 'Highway Driving'), ('reverse_parking', 'Reverse Parking'), ('parallel_parking', 'Parallel Parking'), ('traffic_signals', 'Traffic Signals'), ('hill_driving', 'Hill Driving'), ('night_driving', 'Night Driving'), ('figure_eight', 'Figure-8 Course'), ('free_roam', 'Free Roam')], default='city_driving', max_length=30)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car (4-Wheeler)'), ('bike', 'Bike (2-Wheeler)'), ('scooter', 'Scooter')], default='car', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Brief description shown to the trainee before starting.')),
                ('time_limit_seconds', models.PositiveIntegerField(default=180, help_text='Maximum time allowed for this scenario (seconds).')),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='Minimum score (0-100) required to pass.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_collisions_allowed', models.PositiveIntegerField(default=3, help_text='Maximum boundary/obstacle collisions before auto-fail.')),
                ('total_checkpoints', models.PositiveIntegerField(default=5, help_text='Number of checkpoints on the track.')),
                ('enable_traffic_signals', models.BooleanField(default=True, help_text='Enable traffic signal logic (red/yellow/green).')),
                ('enable_pedestrians', models.BooleanField(default=False, help_text='Spawn AI pedestrians on the track.')),
                ('enable_weather', models.BooleanField(default=False, help_text='Enable dynamic weather effects (rain, fog).')),
                ('enable_reverse_parking', models.BooleanField(default=False, help_text='Include a reverse-parking challenge segment.')),
                ('track_config', models.JSONField(blank=True, help_text='JSON configuration for the track layout consumed by Phaser. Contains boundaries, checkpoint positions, spawn point, etc.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simulation Scenario',
                'verbose_name_plural': 'Simulation Scenarios',
                'ordering': ['vehicle_type', 'difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0, help_text='Final calculated score (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(default=False)),
                ('time_taken_seconds', models.FloatField(default=0, help_text='Actual time the trainee took (seconds).')),
                ('total_distance', models.FloatField(default=0, help_text='Total distance covered in game units.')),
                ('max_speed_reached', models.FloatField(default=0, help_text='Peak speed recorded during the session.')),
                ('average_speed', models.FloatField(default=0, help_text='Average speed over the session.')),
                ('collision_count', models.PositiveIntegerField(default=0, help_text='Number of boundary/obstacle collisions.')),
                ('signal_violations', models.PositiveIntegerField(default=0, help_text='Number of red-light / signal violations.')),
                ('lane_violations', models.PositiveIntegerField(default=0, help_text='Number of wrong-lane / off-road violations.')),
                ('speed_violations', models.PositiveIntegerField(default=0, help_text='Number of over-speed violations.')),
                ('checkpoints_cleared', models.PositiveIntegerField(default=0, help_text='How many checkpoints the trainee passed through.')),
                ('parking_completed', models.BooleanField(default=False, help_text='Whether the parking challenge was completed.')),
                ('parking_accuracy', models.FloatField(default=0, help_text='Parking accuracy percentage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('parking_attempts', models.PositiveIntegerField(default=0, help_text='Number of parking attempts.')),
                ('telemetry_data', models.JSONField(blank=True, help_text='Raw JSON telemetry from the Phaser simulation for replay/analysis.', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='driving_simulation.simulationscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulation Session',
                'verbose_name_plural': 'Simulation Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_number', models.PositiveIntegerField(help_text='1-indexed checkpoint order on the track.')),
                ('time_at_checkpoint', models.FloatField(help_text='Elapsed time (seconds) when this checkpoint was reached.')),
                ('speed_at_checkpoint', models.FloatField(default=0, help_text='Vehicle speed when crossing this checkpoint.')),
                ('penalties_at_checkpoint', models.PositiveIntegerField(default=0, help_text='Cumulative penalties up to this checkpoint.')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_results', to='driving_simulation.simulationsession')),
            ],
            options={
                'verbose_name': 'Checkpoint Result',
                'verbose_name_plural': 'Checkpoint Results',
                'ordering': ['session', 'checkpoint_number'],
                'unique_together': {('session', 'checkpoint_number')},
            },
        ),
    ]
