# Generated by Django 5.2.12 on 2026-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_mocktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.TextField(),
        ),
    ]
