# Generated by Django 5.2.12 on 2026-04-26 05:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0002_remove_instructor_email_remove_instructor_first_name_and_more'),
        ('trainees', '0003_trainee_discount'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_capacity_pct', models.FloatField(default=0.7, help_text="Fraction of each slot's capacity reserved for course trainees (0.0–1.0).", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_sessions_per_trainee_per_day', models.PositiveSmallIntegerField(default=1, help_text='Hard cap on how many sessions a single trainee can be scheduled for in one day.')),
                ('max_reschedule_attempts', models.PositiveSmallIntegerField(default=3, help_text='Maximum times the scheduler will try to re-place an absent trainee.')),
                ('schedule_days_ahead', models.PositiveSmallIntegerField(default=1, help_text='How many calendar days ahead the daily run targets.')),
            ],
            options={
                'verbose_name': 'Scheduling Config',
                'verbose_name_plural': 'Scheduling Config',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField(help_text='1 through 6', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('label', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['slot_number'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(help_text='The date being scheduled for.')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sessions_created', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Warnings, skipped trainees, resource shortfalls, etc.')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null = automated cron job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_type', models.CharField(choices=[('guided', 'Guided (instructor present)'), ('unguided', 'Unguided (supervisor supervised)')], max_length=10)),
                ('trainee_type', models.CharField(choices=[('course', 'Course Trainee'), ('independent', 'Independent Trainee')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sessions', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, help_text='Null for unguided sessions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='instructors.instructor')),
                ('schedule_run', models.ForeignKey(blank=True, help_text='Which scheduler run created this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduling.dailyschedulerun')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='trainees.trainee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='vehicles.vehicle')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='scheduling.timeslot')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='scheduling.track')),
            ],
            options={
                'ordering': ['date', 'slot__slot_number'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, help_text='Number of times the scheduler has tried to re-place this trainee.')),
                ('resolved', models.BooleanField(default=False, help_text='True once the trainee has been successfully placed in a new session.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent scheduler attempt.', null=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_queue_entries', to='trainees.trainee')),
                ('original_session', models.ForeignKey(help_text='The session that was missed (absent).', on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_entries', to='scheduling.session')),
                ('resolved_session', models.ForeignKey(blank=True, help_text='The new session that replaced the missed one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reschedule_entries', to='scheduling.session')),
            ],
            options={
                'verbose_name': 'Reschedule Queue Entry',
                'verbose_name_plural': 'Reschedule Queue',
                'ordering': ['attempt_count', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional reason (e.g. reason for absence).')),
                ('marked_by', models.ForeignKey(help_text='Must be a user with supervisor or admin role (enforced in the view).', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records_marked', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='scheduling.session')),
            ],
            options={
                'ordering': ['-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='TraineePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(help_text='1 = top choice, 6 = last resort.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_preferences', to='scheduling.timeslot')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_preferences', to='trainees.trainee')),
            ],
            options={
                'ordering': ['trainee', 'priority'],
            },
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('slot', 'date', 'vehicle'), name='unique_vehicle_per_slot_day'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('instructor__isnull', False)), fields=('slot', 'date', 'instructor'), name='unique_instructor_per_slot_day'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('slot', 'date', 'trainee'), name='unique_trainee_per_slot_day'),
        ),
        migrations.AddConstraint(
            model_name='traineepreference',
            constraint=models.UniqueConstraint(fields=('trainee', 'slot'), name='unique_trainee_slot_preference'),
        ),
        migrations.AddConstraint(
            model_name='traineepreference',
            constraint=models.UniqueConstraint(fields=('trainee', 'priority'), name='unique_trainee_priority'),
        ),
    ]
