# Generated by Django 5.2.12 on 2026-04-26 06:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_remove_instructor_email_remove_instructor_first_name_and_more'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reschedulequeue',
            options={'ordering': ['priority', '-priority_score', 'attempt_count', 'added_at'], 'verbose_name': 'Reschedule Queue Entry', 'verbose_name_plural': 'Reschedule Queue'},
        ),
        migrations.AddField(
            model_name='reschedulequeue',
            name='priority',
            field=models.PositiveSmallIntegerField(default=3, help_text='Manual urgency level: 1=critical, 5=low. Lower values are scheduled first. Set by admin or supervisor.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='reschedulequeue',
            name='priority_score',
            field=models.PositiveIntegerField(default=0, help_text='Auto-incremented on each failed scheduling attempt. Higher = more urgent within the same priority tier.'),
        ),
        migrations.AddField(
            model_name='session',
            name='supervisor',
            field=models.ForeignKey(default=1, help_text='The supervisor accountable for this session. An instructor temporarily acting as supervisor also fills this field.', on_delete=django.db.models.deletion.PROTECT, related_name='supervised_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='marked_by',
            field=models.ForeignKey(help_text='Must be a supervisor or admin — enforced in the view layer.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reschedulequeue',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reschedulequeue',
            name='last_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulequeue',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedulingconfig',
            name='max_reschedule_attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum scheduler attempts to re-place an absent trainee.'),
        ),
        migrations.AlterField(
            model_name='schedulingconfig',
            name='max_sessions_per_trainee_per_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Hard cap on how many sessions a single trainee can be scheduled for in one day. Enforced in Session.clean().'),
        ),
        migrations.AlterField(
            model_name='schedulingconfig',
            name='schedule_days_ahead',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many calendar days ahead each daily run targets.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Required for guided sessions; must be null for unguided.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='session',
            name='schedule_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scheduling.dailyschedulerun'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot_number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
