# Generated by Django 5.2.12 on 2026-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_reschedulequeue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_type',
            field=models.CharField(choices=[('car', 'Car Track'), ('two_wheeler', 'Two-Wheeler Track (Bike & Scooter)')], default=1, help_text='Determines which vehicle types are permitted on this track.', max_length=20),
            preserve_default=False,
        ),
    ]
