# Generated by Django 5.2.12 on 2026-05-11 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_track_track_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slot_number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='traineepreference',
            name='priority',
            field=models.PositiveSmallIntegerField(help_text='1 = top choice, 8 = last resort.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
