# Generated by Django 5.2.12 on 2026-05-15 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_timeslot_slot_number_and_more'),
        ('trainees', '0005_remove_trainee_photo_trainee_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text="Optional: trainee's reason for requesting a reschedule.")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, help_text="Supervisor's note explaining why the request was rejected.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The supervisor or admin who handled this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reschedule_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='scheduling.session')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='trainees.trainee')),
            ],
            options={
                'verbose_name': 'Reschedule Request',
                'verbose_name_plural': 'Reschedule Requests',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('trainee', 'session'), name='unique_pending_reschedule_request_per_trainee_session')],
            },
        ),
    ]
