# Generated by Django 5.2.12 on 2026-05-15 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_reschedulerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayOrDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date that is off.', unique=True)),
                ('reason', models.CharField(blank=True, help_text="Optional: e.g. 'Dashain', 'Institute Annual Day', etc.", max_length=200)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_days_off', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday / Day Off',
                'verbose_name_plural': 'Holidays / Days Off',
                'ordering': ['date'],
            },
        ),
    ]
