# Generated by Django 5.2.12 on 2026-05-19 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_alter_instructor_images'),
        ('scheduling', '0006_holidayordayoff'),
        ('vehicles', '0002_vehicle_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingconfig',
            name='public_booking_cutoff_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text="How many hours before a slot's start time public bookings close."),
        ),
        migrations.AddField(
            model_name='schedulingconfig',
            name='public_booking_enabled',
            field=models.BooleanField(default=True, help_text='Master switch to enable/disable public slot bookings.'),
        ),
        migrations.AddField(
            model_name='schedulingconfig',
            name='public_session_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Fee charged per public/pay-per-session booking (Rs.).', max_digits=8),
        ),
        migrations.AddField(
            model_name='session',
            name='booking_source',
            field=models.CharField(choices=[('scheduler', 'Auto-Scheduler'), ('manual', 'Manual (Admin/Supervisor)')], default='scheduler', help_text='How this session was created.', max_length=10),
        ),
        migrations.CreateModel(
            name='PublicBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(help_text='Full name of the walk-in trainee.', max_length=200)),
                ('guest_phone', models.CharField(help_text='Phone number for contact.', max_length=15)),
                ('guest_address', models.CharField(blank=True, help_text='Optional address.', max_length=255)),
                ('date', models.DateField()),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('scooter', 'Scooter')], help_text='The vehicle type requested for this session.', max_length=20)),
                ('session_type', models.CharField(choices=[('guided', 'Guided (with instructor)'), ('unguided', 'Unguided (supervisor only)')], default='unguided', help_text='Whether an instructor is needed for this walk-in session.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Fee for this session (snapshot from SchedulingConfig at booking time).', max_digits=8)),
                ('fee_paid', models.BooleanField(default=False, help_text='True = fee has been collected. False = outstanding debt (walk-in did not pay yet).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this booking.')),
                ('created_by', models.ForeignKey(blank=True, help_text='The supervisor/admin who created this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_bookings_created', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, help_text='Assigned instructor (guided sessions only).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_bookings', to='instructors.instructor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_bookings', to='scheduling.timeslot')),
                ('supervisor', models.ForeignKey(blank=True, help_text='The supervisor on duty.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_bookings_supervised', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, help_text='Assigned track.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_bookings', to='scheduling.track')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Assigned vehicle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_bookings', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Public Booking',
                'verbose_name_plural': 'Public Bookings',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('guest_phone', 'slot', 'date'), name='unique_active_public_booking_per_guest_slot_date')],
            },
        ),
    ]
