# Generated by Django 5.2.12 on 2026-04-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('trainee', 'Trainee'), ('supervisor', 'Supervisor')], max_length=20),
        ),
    ]
