# Generated by Django 5.2.12 on 2026-05-19 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits only, 7–15 characters, optional leading +).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
